name: CMake build and test pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: install openblas
      run: sudo apt-get install -y libopenblas-dev
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: make

    - name: Build
      run: cd build && cp -r ../tests/examples/ . && make && ./test

